"""hardening modelo de dados

Adiciona timestamps (`updated_at`) e soft-delete (`deleted_at`) às três
tabelas do domínio, `created_at` em `doadores`, converte `pedidos.categoria`
de VARCHAR para Enum, cria índices de consulta em `pedidos` e nas FKs de
`atendimentos`, e impõe no banco as regras de contato do doador
(CheckConstraint telefone OU email) e unicidade de email.

Revision ID: affcf1b343bb
Revises: 59ed32f51f1d
Create Date: 2026-06-02 07:34:13.115895

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "affcf1b343bb"
down_revision: str | None = "59ed32f51f1d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Mapa de valores legados de `pedidos.categoria` (gravados como texto livre pelo
#: front antigo, com acento/espaço/minúscula) para os labels do `categoria_enum`.
#: A conversão VARCHAR -> Enum falha em Postgres se sobrar qualquer linha cujo
#: valor não corresponda exatamente a um label; por isso normalizamos antes do
#: ALTER. Em base vazia (caso da suíte de testes) os UPDATEs são no-op.
_MAPA_CATEGORIAS_LEGADAS: dict[str, str] = {
    "ração": "RACAO",
    "racao": "RACAO",
    "transporte": "TRANSPORTE",
    "veterinário": "VETERINARIO",
    "veterinario": "VETERINARIO",
    "lar temporário": "LAR_TEMPORARIO",
    "lar temporario": "LAR_TEMPORARIO",
    "lar_temporario": "LAR_TEMPORARIO",
    "resgate": "RESGATE",
}

#: Default seguro para qualquer valor não reconhecido. Escolhemos RESGATE por ser
#: a categoria mais genérica/abrangente: classificar errado um pedido como
#: "resgate" é menos enganoso para o público do que forçá-lo em uma categoria
#: específica (ração, transporte, etc.).
_CATEGORIA_DEFAULT: str = "RESGATE"


def _normalizar_categorias() -> None:
    """Converte os valores legados de `pedidos.categoria` para os labels do enum.

    Roda enquanto a coluna ainda é VARCHAR, antes do `alter_column`. É idempotente
    e seguro tanto em base vazia (UPDATEs no-op) quanto populada, e compatível com
    SQLite e Postgres (usa apenas SQL padrão: TRIM/LOWER e comparação de igualdade).

    Args:
        Nenhum.

    Returns:
        None.

    Side Effects:
        Reescreve a coluna `pedidos.categoria` mapeando cada valor legado para o
        label correspondente; valores já no formato do enum ou desconhecidos caem
        no default seguro `RESGATE`.
    """
    labels = set(_MAPA_CATEGORIAS_LEGADAS.values())

    # 1) Mapeia os valores legados conhecidos (case/trim-insensitive) para o label.
    for legado, label in _MAPA_CATEGORIAS_LEGADAS.items():
        op.execute(
            sa.text(
                "UPDATE pedidos SET categoria = :label " "WHERE LOWER(TRIM(categoria)) = :legado"
            ).bindparams(label=label, legado=legado)
        )

    # 2) Qualquer valor remanescente que não seja um label válido vira o default.
    placeholders = ", ".join(f":l{i}" for i in range(len(labels)))
    params = {f"l{i}": label for i, label in enumerate(labels)}
    params["default"] = _CATEGORIA_DEFAULT
    op.execute(
        sa.text(
            f"UPDATE pedidos SET categoria = :default " f"WHERE categoria NOT IN ({placeholders})"
        ).bindparams(**params)
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("atendimentos", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f("ix_atendimentos_doador_id"), ["doador_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_atendimentos_pedido_id"), ["pedido_id"], unique=False)

    with op.batch_alter_table("doadores", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.create_unique_constraint("uq_doadores_email", ["email"])
        batch_op.create_check_constraint(
            "ck_doadores_contato_obrigatorio",
            "telefone IS NOT NULL OR email IS NOT NULL",
        )

    # Normaliza os valores legados de `categoria` (ainda VARCHAR) para os labels
    # do enum ANTES do ALTER, evitando que a conversão de tipo falhe no Postgres
    # de produção por causa de linhas com valores do front antigo.
    _normalizar_categorias()

    categoria_enum = sa.Enum(
        "RACAO",
        "TRANSPORTE",
        "VETERINARIO",
        "LAR_TEMPORARIO",
        "RESGATE",
        name="categoria_enum",
    )
    # No Postgres o `ALTER COLUMN ... TYPE categoria_enum` exige que o tipo já
    # exista — `alter_column` NÃO o cria automaticamente (ao contrário de
    # `add_column`). Criamos o tipo aqui; em SQLite (enum não-nativo) é no-op.
    categoria_enum.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table("pedidos", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column(
            "categoria",
            existing_type=sa.VARCHAR(length=60),
            type_=categoria_enum,
            existing_nullable=False,
            # No Postgres a conversão VARCHAR -> Enum exige um USING explícito; os
            # dados já foram normalizados para labels válidos acima. Ignorado pelo
            # SQLite (que recria a tabela via batch).
            postgresql_using="categoria::categoria_enum",
        )
        batch_op.create_index(batch_op.f("ix_pedidos_categoria"), ["categoria"], unique=False)
        batch_op.create_index(batch_op.f("ix_pedidos_data_criacao"), ["data_criacao"], unique=False)
        batch_op.create_index(batch_op.f("ix_pedidos_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_pedidos_urgencia"), ["urgencia"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pedidos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pedidos_urgencia"))
        batch_op.drop_index(batch_op.f("ix_pedidos_status"))
        batch_op.drop_index(batch_op.f("ix_pedidos_data_criacao"))
        batch_op.drop_index(batch_op.f("ix_pedidos_categoria"))
        batch_op.alter_column(
            "categoria",
            existing_type=sa.Enum(
                "RACAO",
                "TRANSPORTE",
                "VETERINARIO",
                "LAR_TEMPORARIO",
                "RESGATE",
                name="categoria_enum",
            ),
            type_=sa.VARCHAR(length=60),
            existing_nullable=False,
            postgresql_using="categoria::text",
        )
        batch_op.drop_column("deleted_at")
        batch_op.drop_column("updated_at")

    # Remove o tipo enum no Postgres após a coluna voltar a VARCHAR (no-op no SQLite).
    sa.Enum(name="categoria_enum").drop(op.get_bind(), checkfirst=True)

    with op.batch_alter_table("doadores", schema=None) as batch_op:
        batch_op.drop_constraint("ck_doadores_contato_obrigatorio", type_="check")
        batch_op.drop_constraint("uq_doadores_email", type_="unique")
        batch_op.drop_column("deleted_at")
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")

    with op.batch_alter_table("atendimentos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_atendimentos_pedido_id"))
        batch_op.drop_index(batch_op.f("ix_atendimentos_doador_id"))
        batch_op.drop_column("deleted_at")
        batch_op.drop_column("updated_at")

    # ### end Alembic commands ###
