"""hardening modelo de dados

Adiciona timestamps (`updated_at`) e soft-delete (`deleted_at`) às três
tabelas do domínio, `created_at` em `doadores`, converte `pedidos.categoria`
de VARCHAR para Enum, cria índices de consulta em `pedidos` e nas FKs de
`atendimentos`, e impõe no banco as regras de contato do doador
(CheckConstraint telefone OU email) e unicidade de email.

Revision ID: affcf1b343bb
Revises: 59ed32f51f1d
Create Date: 2026-06-02 07:34:13.115895

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "affcf1b343bb"
down_revision: str | None = "59ed32f51f1d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("atendimentos", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f("ix_atendimentos_doador_id"), ["doador_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_atendimentos_pedido_id"), ["pedido_id"], unique=False)

    with op.batch_alter_table("doadores", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.create_unique_constraint("uq_doadores_email", ["email"])
        batch_op.create_check_constraint(
            "ck_doadores_contato_obrigatorio",
            "telefone IS NOT NULL OR email IS NOT NULL",
        )

    with op.batch_alter_table("pedidos", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column(
            "categoria",
            existing_type=sa.VARCHAR(length=60),
            type_=sa.Enum(
                "RACAO",
                "TRANSPORTE",
                "VETERINARIO",
                "LAR_TEMPORARIO",
                "RESGATE",
                name="categoria_enum",
            ),
            existing_nullable=False,
        )
        batch_op.create_index(batch_op.f("ix_pedidos_categoria"), ["categoria"], unique=False)
        batch_op.create_index(batch_op.f("ix_pedidos_data_criacao"), ["data_criacao"], unique=False)
        batch_op.create_index(batch_op.f("ix_pedidos_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_pedidos_urgencia"), ["urgencia"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pedidos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pedidos_urgencia"))
        batch_op.drop_index(batch_op.f("ix_pedidos_status"))
        batch_op.drop_index(batch_op.f("ix_pedidos_data_criacao"))
        batch_op.drop_index(batch_op.f("ix_pedidos_categoria"))
        batch_op.alter_column(
            "categoria",
            existing_type=sa.Enum(
                "RACAO",
                "TRANSPORTE",
                "VETERINARIO",
                "LAR_TEMPORARIO",
                "RESGATE",
                name="categoria_enum",
            ),
            type_=sa.VARCHAR(length=60),
            existing_nullable=False,
        )
        batch_op.drop_column("deleted_at")
        batch_op.drop_column("updated_at")

    with op.batch_alter_table("doadores", schema=None) as batch_op:
        batch_op.drop_constraint("ck_doadores_contato_obrigatorio", type_="check")
        batch_op.drop_constraint("uq_doadores_email", type_="unique")
        batch_op.drop_column("deleted_at")
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")

    with op.batch_alter_table("atendimentos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_atendimentos_pedido_id"))
        batch_op.drop_index(batch_op.f("ix_atendimentos_doador_id"))
        batch_op.drop_column("deleted_at")
        batch_op.drop_column("updated_at")

    # ### end Alembic commands ###
